import 'package:fighting_game/enums/character_type.dart';
import 'package:fighting_game/models/hero_info.dart';
import 'package:fighting_game/utils/select_per_tileset.dart';
import 'package:flutter/material.dart';

/// Danh sách 12 anh hùng chia làm 2 phe/hàng:
/// Hàng 1: Pháp Sư & Hiệp Sĩ (Mages & Knights)
/// Hàng 2: Samurai & Quỷ Cốt (Samurais & Skeletons)
const List<HeroInfo> kHeroRoster = [
  // --- HÀNG 1: PHÁP SƯ & HIỆP SĨ ---
  HeroInfo(
    type: CharacterType.fireWizard,
    name: 'HỎA DIỆM PHÁP SƯ',
    title: 'Hỏa Long Tôn Giả (Ignis)',
    role: 'Pháp Sư - Hỏa Lực',
    pillarTile: SelectPerTile.pillarRed,
    badgeTile: SelectPerTile.badgeCrown,
    gemTile: SelectPerTile.gemRuby,
    primaryColor: Color(0xFFFF5722),
    atkRating: 0.95,
    defRating: 0.50,
    spdRating: 0.70,
    rngRating: 0.95,
    ultimateName: 'Hỏa Long Bộc Phá',
    description: 'Sở hữu ngọn lửa cổ xưa thiêu rụi mọi phòng ngự. Cầu lửa có tầm bắn toàn màn hình.',
    idleFrames: 7,
  ),
  HeroInfo(
    type: CharacterType.lightningWizard,
    name: 'LÔI ĐIỆN PHÁP SƯ',
    title: 'Cuồng Lôi Tiên Sinh (Voltis)',
    role: 'Pháp Sư - Khống Chế',
    pillarTile: SelectPerTile.pillarBlue,
    badgeTile: SelectPerTile.badgeCrown,
    gemTile: SelectPerTile.gemSapphire,
    primaryColor: Color(0xFF00E5FF),
    atkRating: 0.90,
    defRating: 0.55,
    spdRating: 0.85,
    rngRating: 0.88,
    ultimateName: 'Thiên Lôi Giáng Lâm',
    description: 'Tốc độ xuất chiêu cực nhanh như tia chớp, giật điện làm tê liệt kẻ thù tức khắc.',
    idleFrames: 7,
  ),
  HeroInfo(
    type: CharacterType.wandererMagician,
    name: 'LÃNG KHÁCH PHÁP SƯ',
    title: 'Bí Ẩn Hư Không (Aether)',
    role: 'Pháp Sư - Hư Không',
    pillarTile: SelectPerTile.pillarPurple,
    badgeTile: SelectPerTile.badgeCrown,
    gemTile: SelectPerTile.gemRuby,
    primaryColor: Color(0xFFAB47BC),
    atkRating: 0.85,
    defRating: 0.60,
    spdRating: 0.80,
    rngRating: 0.90,
    ultimateName: 'Hư Không Trảm Kích',
    description: 'Bậc thầy thuật không gian, biến ảo khôn lường và tạo vết nứt hủy diệt tầm xa.',
    idleFrames: 8,
  ),
  HeroInfo(
    type: CharacterType.knight1,
    name: 'THÁNH HIỆP SĨ',
    title: 'Kỵ Sĩ Ánh Sáng (Arthur)',
    role: 'Đỡ Đòn - Toàn Diện',
    pillarTile: SelectPerTile.pillarRed,
    badgeTile: SelectPerTile.badgeShield,
    gemTile: SelectPerTile.gemRuby,
    primaryColor: Color(0xFFFFD54F),
    atkRating: 0.80,
    defRating: 0.92,
    spdRating: 0.65,
    rngRating: 0.60,
    ultimateName: 'Thánh Kiếm Phán Quyết',
    description: 'Giáp thép kiên cố cùng khiên thần hộ mệnh. Sát thương phản hồi cực kỳ kinh hoàng.',
    idleFrames: 4,
  ),
  HeroInfo(
    type: CharacterType.knight2,
    name: 'HOÀNG GIA HIỆP SĨ',
    title: 'Thanh Kiếm Vương Triều (Galahad)',
    role: 'Đấu Sĩ - Tiên Phong',
    pillarTile: SelectPerTile.pillarBlue,
    badgeTile: SelectPerTile.badgeShield,
    gemTile: SelectPerTile.gemSapphire,
    primaryColor: Color(0xFF42A5F5),
    atkRating: 0.85,
    defRating: 0.80,
    spdRating: 0.75,
    rngRating: 0.65,
    ultimateName: 'Hoàng Gia Đột Kích',
    description: 'Tướng tiên phong của vương quốc, sở hữu những đòn xông trận dũng mãnh và kiếm thuật thép.',
    idleFrames: 4,
  ),
  HeroInfo(
    type: CharacterType.knight3,
    name: 'HẮC HIỆP SĨ',
    title: 'Hắc Giáp Tử Thần (Mordred)',
    role: 'Đấu Sĩ - Bạo Lực',
    pillarTile: SelectPerTile.pillarPurple,
    badgeTile: SelectPerTile.badgeShield,
    gemTile: SelectPerTile.gemRuby,
    primaryColor: Color(0xFF8E24AA),
    atkRating: 0.92,
    defRating: 0.85,
    spdRating: 0.60,
    rngRating: 0.65,
    ultimateName: 'Hắc Long Trọng Trảm',
    description: 'Kỵ sĩ bóng đêm với thanh đại kiếm khổng lồ, nghiền nát mọi tuyến phòng ngự.',
    idleFrames: 4,
  ),

  // --- HÀNG 2: SAMURAI & TỬ LINH ---
  HeroInfo(
    type: CharacterType.samurai,
    name: 'SAMURAI ĐỘC HÀNH',
    title: 'Phong Kiếm Tuyệt Luân (Kenji)',
    role: 'Sát Thủ - Bão Kiếm',
    pillarTile: SelectPerTile.pillarRed,
    badgeTile: SelectPerTile.badgeSwords,
    gemTile: SelectPerTile.gemRuby,
    primaryColor: Color(0xFFFF1744),
    atkRating: 0.96,
    defRating: 0.58,
    spdRating: 0.95,
    rngRating: 0.70,
    ultimateName: 'Vô Cực Tuyệt Kiếm',
    description: 'Đao pháp xuất quỷ nhập thần với tốc độ ánh sáng. Chuỗi liên hoàn kiếm hạ gục kẻ địch tức thì.',
    idleFrames: 6,
  ),
  HeroInfo(
    type: CharacterType.samuraiArcher,
    name: 'SAMURAI CUNG THỦ',
    title: 'Tật Phong Thần Tiễn (Hanzo)',
    role: 'Xạ Thủ - Tầm Xa',
    pillarTile: SelectPerTile.pillarGreen,
    badgeTile: SelectPerTile.badgeSwords,
    gemTile: SelectPerTile.gemEmerald,
    primaryColor: Color(0xFF00E676),
    atkRating: 0.88,
    defRating: 0.50,
    spdRating: 0.90,
    rngRating: 0.98,
    ultimateName: 'Bão Tiễn Đoạt Mạng',
    description: 'Bách phát bách trúng ở cự ly xa. Mũi tên xé gió giữ khoảng cách giao tranh an toàn.',
    idleFrames: 9,
  ),
  HeroInfo(
    type: CharacterType.samuraiCommander,
    name: 'SAMURAI THỐNG LĨNH',
    title: 'Chiến Tướng Bá Đạo (Nobunaga)',
    role: 'Đấu Sĩ - Uy Áp',
    pillarTile: SelectPerTile.pillarBlue,
    badgeTile: SelectPerTile.badgeSwords,
    gemTile: SelectPerTile.gemSapphire,
    primaryColor: Color(0xFF1E88E5),
    atkRating: 0.90,
    defRating: 0.78,
    spdRating: 0.80,
    rngRating: 0.72,
    ultimateName: 'Thiên Hạ Bá Quyền',
    description: 'Thống soái trận tiền sở hữu nhát chém khí phách ngút trời, xoay chuyển cục diện trận chiến.',
    idleFrames: 5,
  ),
  HeroInfo(
    type: CharacterType.skeletonWarrior,
    name: 'TỬ LINH CHIẾN BINH',
    title: 'Hài Cốt Trỗi Dậy (Krag)',
    role: 'Đấu Sĩ - Bất Tử',
    pillarTile: SelectPerTile.pillarPurple,
    badgeTile: SelectPerTile.badgeSkull,
    gemTile: SelectPerTile.gemRuby,
    primaryColor: Color(0xFF9C27B0),
    atkRating: 0.82,
    defRating: 0.75,
    spdRating: 0.75,
    rngRating: 0.65,
    ultimateName: 'Oán Hồn Bùng Nổ',
    description: 'Chiến binh từ cõi âm không biết đau đớn, liên tục ép sân bằng những cú bổ kiếm tàn bạo.',
    idleFrames: 7,
  ),
  HeroInfo(
    type: CharacterType.skeletonArcher,
    name: 'TỬ LINH XẠ THỦ',
    title: 'Tử Xạ Hư Không (Skel\'Arch)',
    role: 'Xạ Thủ - Độc Dược',
    pillarTile: SelectPerTile.pillarGreen,
    badgeTile: SelectPerTile.badgeSkull,
    gemTile: SelectPerTile.gemEmerald,
    primaryColor: Color(0xFF43A047),
    atkRating: 0.85,
    defRating: 0.45,
    spdRating: 0.88,
    rngRating: 0.95,
    ultimateName: 'Mũi Tên Hắc Ám',
    description: 'Tung ra những phát bắn mang độc tố tử linh, làm chậm và rút kiệt sinh lực đối phương.',
    idleFrames: 7,
  ),
  HeroInfo(
    type: CharacterType.skeletonSpearman,
    name: 'TỬ LINH THƯƠNG THỦ',
    title: 'Trường Thương Địa Ngục (Spearhead)',
    role: 'Đấu Sĩ - Đột Kích',
    pillarTile: SelectPerTile.pillarRed,
    badgeTile: SelectPerTile.badgeSkull,
    gemTile: SelectPerTile.gemRuby,
    primaryColor: Color(0xFFE53935),
    atkRating: 0.86,
    defRating: 0.70,
    spdRating: 0.82,
    rngRating: 0.80,
    ultimateName: 'Xung Kích Tử Thần',
    description: 'Tầm đâm trường thương cực dài và hiểm hóc, xuyên thủng mọi lớp giáp kiên cố.',
    idleFrames: 7,
  ),
];
